### ISSUE TITLE
implement programatic expansion of the metadata

### ISSUE THREAD

**Issue by sopos** [psss/fmf#152]
Example:
imagine this metadata:
```yaml
/old-syntax:
        environment+:
            rsyslogSyntax: old
        /x509_name:
            extra-summary: CONDITIONAL_PHASES_BL=ossl rsyslogSyntax=old /rsyslog/Sanity/gnutls-openssl
/new-syntax:
        environment+:
            rsyslogSyntax: new
        /x509_name:
            extra-summary: CONDITIONAL_PHASES_BL=ossl rsyslogSyntax=new /rsyslog/Sanity/gnutls-openssl
```

to simplify it one could use something like:
```yaml
%for syntax in [old, new]:
/%syntax%-syntax:
        environment+:
            rsyslogSyntax: %syntax%
        /x509_name:
            extra-summary: CONDITIONAL_PHASES_BL=ossl rsyslogSyntax=%syntax% /rsyslog/Sanity/gnutls-openssl
%rof
```

For more metadata worth simplification see https://github.com/RedHat-SP-Security/tests/blob/69e188bad1da05dbdbf21d102bcec25655ec9a3b/rsyslog/Sanity/gnutls-openssl/main.fmf#L57
The life metadata cannot be used directly due to nitrate TC mapping but it could be easily without it.

The fmf files would be pre-processed using a metalanguage and then processed as usual.

**Comment by sopos** [comment]
another real use case (from rhel6 :) :
There is a dual component _rsyslog_ and _rsyslog7_. The test normally require _rsyslog*_ packages. However if the _rsyslog7_ is going to be tested all such requires should be basicaly replaces with _rsyslog7*_.
Currently, this can be achieved by implementing to all the tests following adjust:
```yaml
adjust:
  - require-:
      - rsyslog
    require+:
      - rsyslog7
    when: component = rsyslog7
```
plus for all the required sub-packages.

An elegant solution might be to use the macro language:
```yaml
set rsyslog=rsyslog7
require:
  - ${rsyslog}
  - ${rsyslog}-gnutls
```
So the only require thing would be to replace all the requirement `rsyslog` with `${rsyslog}`.

Another solution might be to use _templates_.
