### ISSUE TITLE
Broken inheritance since v0.3

### ISSUE THREAD

**Issue by jkrysl** [psss/fmf#25]
Updating to FMF version 0.3 breaks the inheritance feature. All of the missing attributes in 0.3 are defined somewhere in the parents and they are not getting passed down to the child.

# 0.2:
$ fmf --name vdo/vdo_cli/various_commands/stop_start_rebuild_success
tests/vdo/vdo_cli/various_commands/stop_start_rebuild_success
component: vdo and kmod-kvdo
description: Testing 'vdo stop' and 'vdo start' with '--forceRebuild', commands should succeed
requires_install: vdo and kmod-kvdo
requires_setup: vdo/setup/storage/setup_* and vdo/setup/create_vdo
test: stop_start_rebuild.py
tester: me...
tier: 1
time: 1 min
vdo_name: vdo_test

# 0.3:
$ fmf --name vdo/vdo_cli/various_commands/stop_start_rebuild_success
tests/vdo/vdo_cli/various_commands/stop_start_rebuild_success
description: "Testing 'vdo stop' and 'vdo start' with '--forceRebuild', commands should succeed"
test: 'stop_start_rebuild.py'
tier: 1

**Comment by jkrysl** [comment]
This seems to be related to 70b6207f71b4e00622f55e1420c3e57e061a71a0, as I am defining the same leaf (quite deep in hierarchy) from 2 places:
```
# fmf --name vdo/vdo_cli/various_commands/stop_start_rebuild_success
tests/vdo/vdo_cli/various_commands/stop_start_rebuild_success
description: "Testing 'vdo stop' and 'vdo start' with '--forceRebuild', commands should succeed"
something: True
test: 'stop_start_rebuild.py'
tier: 1

# mv vdo.fmf ..

# fmf --name vdo/vdo_cli/various_commands/stop_start_rebuild_success
tests/vdo/vdo_cli/various_commands/stop_start_rebuild_success
component: ['vdo', 'kmod-kvdo']
description: "Testing 'vdo stop' and 'vdo start' with '--forceRebuild', commands should succeed"
requires_install: ['vdo', 'kmod-kvdo']
requires_setup: ['vdo/setup/storage/setup_*', 'vdo/setup/create_vdo']
test: 'stop_start_rebuild.py'
tester: 'me...'
tier: 1
time: '1 min'
vdo_name: 'vdo_test'

# cat ../vdo.fmf
/vdo_cli/various_commands/stop_start_rebuild_success:
  something: True

# cat vdo/vdo_cli/various_commands/main.fmf
description: Testing various commands for 'vdo'
time: 1 min
requires_setup+: [vdo/setup/create_vdo]
/stop_start_rebuild_success:
  description: Testing 'vdo stop' and 'vdo start' with '--forceRebuild', commands should succeed
  test: stop_start_rebuild.py
  tier: 1
```

It appears FMF now ignores any data in between `vdo.fmf` and `/stop_start_rebuild_success:` in `vdo/vdo_cli/various_commands/main.fmf`. Version 0.2 for comparision (with `vdo.fmf`):
```
# fmf --name vdo/vdo_cli/various_commands/stop_start_rebuild_success
tests/vdo/vdo_cli/various_commands/stop_start_rebuild_success
component: vdo and kmod-kvdo
description: Testing 'vdo stop' and 'vdo start' with '--forceRebuild', commands should succeed
requires_install: vdo and kmod-kvdo
requires_setup: vdo/setup/storage/setup_* and vdo/setup/create_vdo
test: stop_start_rebuild.py
tester: me...
tier: 1
time: 1 min
vdo_name: vdo_test

tests/vdo/vdo_cli/various_commands/stop_start_rebuild_success
something: True
```
