### ISSUE TITLE
RFE: add support for downloading resources from URL or GIT to project/metadata specification

### ISSUE THREAD

**Issue by jscotka** [psss/fmf#3]
I would like to have there some similar syntax what I has in my PoC for metadata downloading some files from URLs or git repositories.
##Usestory
 It allows me to have metadata and load them also from network or another location
see example config lines like: https://github.com/fedora-modularity/meta-test-family/blob/master/mtf/metadata/examples/general-component/tests/metadata.yaml#L8
```
download_urls:
  downloaded_test.py: "https://raw.githubusercontent.com/fedora-modularity/meta-test-family/devel/mtf/metadata/examples/general-component/tests/simple.py"
  somedir/metadata.yaml: "some link to another metadata"
clone_gits:
  downloaded_git: "https://github.com/container-images/memcached.git"
```
It will clone or dowload files locally as files or subdirectories

## How it should work
 * load metadata
 * find these items what downloads something
 * reload metadata again with these updates
(do not do it recursively) -> can causes loops, to allow just one round of this reloading

## summary
 * have stored metadata elegantly in various places, easy to use
  * eg. I want to load metadata for some generic tests / linters and run them together with my tests what are in  some github repo
  * or another location on same disc means that I can add there this url param with file:///... for example
 * this is important feature for my usecases in MTF
 * could be implemented by separated class, module, file, whatwill use metadata and this recursive loading could be lead externally or via some option, cmd line  argument. I think it is beneficial to have it directly there and not as part of MTF, what will do this part and interpret this items in metadata files
