### ISSUE TITLE
[RFE] add option to print error/warning if some test case identifiers are not unique

### ISSUE THREAD

**Issue by akhait** [psss/fmf#49]
According to documentation, test case identifiers should be unique within current fmf structure. However, it is possible to work with a configuration text file, that has duplicated identifiers.

Example:
```
/python/Sanity/sys:
  component:
    - python3
  environment:
    PYTHON: /usr/libexec/platform-python
    PACKAGES: python3

/python/Sanity/sys:
  component:
    - python
```
Having that `test.fmf`, `fmf show` in the root directory shows
```
/Sanity/sys/test/CoreOS/python/Sanity/sys
component: python
```
so the first test was overwritten by the second one with duplicated identifier with no error returned.

As a user, I would like to be aware of the fact that I have duplicated test case identifiers in `.fmf` file, either with a visible warning or error and abortion of execution.
