### ISSUE TITLE
implement nested fmf structures

### ISSUE THREAD

**Issue by sopos** [psss/fmf#82]
Image a node where I define a reference to another git repo where the branch continues.
I can image a reserved attribute 
```
fmf_subtree:
  url: https://github.com/...
  reference: master
```
such repo would be pulled and the tree would be simply extended by this part.

It is still questionable how the inheritance should behave at such points where a new _fmf_ tree begins. This might be controlled by another attribute of _fmf_subtree_, e.g. boolean _inheritance_.
```
fmf_subtree:
  url: https://github.com/...
  reference: master
  inheritance: true
```

**Comment by sopos** [comment]
one more possible extension would be usage of _path_ attribute which would allow one to use just a sub-tree of the target repo which could be another form of filtering or selecting just a subset of the metadata (e.g. include plans only, or tests only if organized separately).
```
fmf_subtree:
  url: https://github.com/RedHat-SP-Security/tests
  reference: master
  inheritance: true
  path: /usbguard
```
